receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:5317"
      http:
        endpoint: "0.0.0.0:5318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 100
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 100
  resource:
    attributes:
      - key: service.name
        value: "test-service"
        action: upsert
      - key: environment
        value: "development"
        action: upsert

exporters:
  logging:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "otel-data"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging, elasticsearch]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging, elasticsearch]